services:
  - type: web
    name: oms-api
    env: python
    plan: free
    autoDeploy: true
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: TZ
        value: Asia/Kuala_Lumpur
